CREATE SEQUENCE RENNESFREITAS.GAMES_ID_SEQUENCE
	MINVALUE 1
	START WITH 3
	INCREMENT BY 2
	NOCACHE;

DROP SEQUENCE RENNESFREITAS.GAMES_ID_SEQUENCE;

CREATE SEQUENCE RENNESFREITAS.PLATAFORMS_ID_SEQUENCE
	MINVALUE 0
	START WITH 2
	INCREMENT BY 2
	NOCACHE;

DROP SEQUENCE RENNESFREITAS.PLATAFORMS_ID_SEQUENCE;

--About Triggers: https://stackoverflow.com/questions/18741342/ora-04082-new-or-old-references-not-allowed-in-table-level-triggers
CREATE TRIGGER RENNESFREITAS.GAMES_GAMES_ID_GEN
BEFORE INSERT
	ON RENNESFREITAS.GAMES
	FOR EACH ROW
--DECLARE
--
BEGIN 
	:NEW.GAMES_ID := RENNESFREITAS.GAMES_ID_SEQUENCE.NEXTVAL;
END;

DROP TRIGGER RENNESFREITAS.GAMES_GAMES_ID_GEN;

CREATE TRIGGER RENNESFREITAS.PLATAFORMS_PLATAFORMS_ID_GEN
BEFORE INSERT
	ON RENNESFREITAS.PLATAFORMS 
	FOR EACH ROW 
BEGIN 
	:NEW.PLATAFORMS_ID := RENNESFREITAS.PLATAFORMS_ID_SEQUENCE.NEXTVAL;
END;

DROP TRIGGER RENNESFREITAS.PLATAFORMS_PLATAFORMS_ID_GEN;