DROP TABLE RENNESFREITAS.GAMES;
DROP TABLE RENNESFREITAS.PLATAFORMS;
DROP TABLE RENNESFREITAS.RELEASES;

CREATE TABLE RENNESFREITAS.GAMES --PARENT 1
(
	GAMES_ID number NOT NULL,
	NAME varchar2(255) UNIQUE,
	PUBLISHER varchar2(255), 
	CONSTRAINT GAMES_ID_PK PRIMARY KEY (GAMES_ID)
);

CREATE TABLE RENNESFREITAS.PLATAFORMS -- PARENT 1
(
	PLATAFORMS_ID NUMBER NOT NULL,
	NAME varchar2(255) UNIQUE,
	CONSTRAINT PLATAFORMS_ID_PK PRIMARY KEY (PLATAFORMS_ID)
);

CREATE TABLE RENNESFREITAS.RELEASES --CHILD N (INTERMEDIÁRIA)
(
	GAME NUMBER NOT NULL,
	PLATAFORM NUMBER NOT NULL,
	RELEASEDATE DATE DEFAULT SYSDATE,
	VERSION NUMBER NOT NULL,
	CONSTRAINT RELEASES_PK PRIMARY KEY (GAME, PLATAFORM, VERSION)
);

ALTER TABLE RENNESFREITAS.RELEASES
ADD CONSTRAINT fk_RELEASESPLATAFOM
	FOREIGN KEY (PLATAFORM)
	REFERENCES RENNESFREITAS.PLATAFORMS (PLATAFORMS_ID);

ALTER TABLE RENNESFREITAS.RELEASES
ADD CONSTRAINT fk_RELEASESGAME
	FOREIGN KEY (GAME)
	REFERENCES RENNESFREITAS.GAMES (GAMES_ID);
--Relacionamento 1:N https://www.devmedia.com.br/exemplo-pratico-regras-e-tipos-de-relacionamentos-sql-server-2008-parte-3/18409
